"""Initial migration with posts table

Revision ID: 24fe39db1d1a
Revises: 
Create Date: 2024-06-24 15:27:20.694005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24fe39db1d1a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('image_file', sa.String(length=20), nullable=True))
    op.add_column('post', sa.Column('video_file', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'video_file')
    op.drop_column('post', 'image_file')
    # ### end Alembic commands ###
